FROM node:20-alpine as base
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/web/package.json apps/web/package.json
COPY packages/common/package.json packages/common/package.json
RUN npm i -g pnpm@9 && pnpm install --frozen-lockfile
COPY packages ./packages
COPY apps/web ./apps/web
WORKDIR /app/apps/web
RUN pnpm build
EXPOSE 3000
CMD ["pnpm", "start"]
