name: CD API
on:
  push:
    tags:
      - 'api-v*'
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/parking-api:latest,${{ secrets.DOCKERHUB_USERNAME }}/parking-api:${{ github.ref_name }}
